### ISSUE TITLE
Heroku App Crashed

### ISSUE THREAD

**Issue by jcornelius** [ninelabs/ninelabs.com#117]
I setup a new Heroku app at https://ninelabs-staging.herokuapp.com/ for the `new-content-structure` branch. 

![ninelabs-staging-heroku](https://cloud.githubusercontent.com/assets/366136/10268251/9da0eed8-6a80-11e5-875a-8254015a4d71.png)

It auto-deploys okay according to the Heroku dashboard, but visiting in the browser says there's an error. Here's the log:

Hey @johnagan, any ideas?

```
2015-10-04T14:00:59.705876+00:00 heroku[api]: Release v7 created by jc@ninelabs.com
2015-10-04T14:00:59.973057+00:00 heroku[web.1]: State changed from crashed to starting
2015-10-04T14:01:05.614066+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 54694`
2015-10-04T14:01:08.414448+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/rack-jekyll-0.3.5/lib/rack/jekyll.rb:10:in `initialize': uninitialized constant YAML (NameError)
2015-10-04T14:01:08.414493+00:00 app[web.1]: 	from /app/config.ru:2:in `new'
2015-10-04T14:01:08.414515+00:00 app[web.1]: 	from /app/config.ru:2:in `block in <main>'
2015-10-04T14:01:08.414535+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2015-10-04T14:01:08.414594+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2015-10-04T14:01:08.414555+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
2015-10-04T14:01:08.414614+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2015-10-04T14:01:08.414633+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2015-10-04T14:01:08.414574+00:00 app[web.1]: 	from /app/config.ru:in `new'
2015-10-04T14:01:08.414652+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
2015-10-04T14:01:08.414671+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2015-10-04T14:01:08.414690+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
2015-10-04T14:01:08.414710+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
2015-10-04T14:01:08.414730+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2015-10-04T14:01:08.414749+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
2015-10-04T14:01:08.414788+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `load'
2015-10-04T14:01:08.414768+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
2015-10-04T14:01:08.414807+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `<main>'
2015-10-04T14:01:09.340931+00:00 heroku[web.1]: Process exited with status 1
2015-10-04T14:01:09.352153+00:00 heroku[web.1]: State changed from starting to crashed
2015-10-04T14:01:14.453229+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ninelabs-staging.herokuapp.com request_id=14368929-79c5-4730-9c6e-1a8f31c738b8 fwd="98.242.119.27" dyno= connect= service= status=503 bytes=
```

**Comment by jcornelius** [comment]
Turns out this is an issue with Jekyll and Rack. See https://github.com/jekyll/jekyll/issues/4011
